// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqaxaSIwEGbgFSOgi8jDNpTK7bULqsVgY',
    appId: '1:1038460710831:web:e102bc104400f3de17c95a',
    messagingSenderId: '1038460710831',
    projectId: 'inventory-management-app-act12',
    authDomain: 'inventory-management-app-act12.firebaseapp.com',
    storageBucket: 'inventory-management-app-act12.firebasestorage.app',
    measurementId: 'G-487YLWVSB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN7G5c0E_t2tUy9GQPEo-EvcH0jgWeTE0',
    appId: '1:1038460710831:android:8d18b18d99108dd817c95a',
    messagingSenderId: '1038460710831',
    projectId: 'inventory-management-app-act12',
    storageBucket: 'inventory-management-app-act12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbaSHkEKcq-VaGuKCB2KtPSzHOc6-xYlc',
    appId: '1:1038460710831:ios:d8155bf0e84eae0117c95a',
    messagingSenderId: '1038460710831',
    projectId: 'inventory-management-app-act12',
    storageBucket: 'inventory-management-app-act12.firebasestorage.app',
    iosBundleId: 'com.example.act12InventoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbaSHkEKcq-VaGuKCB2KtPSzHOc6-xYlc',
    appId: '1:1038460710831:ios:d8155bf0e84eae0117c95a',
    messagingSenderId: '1038460710831',
    projectId: 'inventory-management-app-act12',
    storageBucket: 'inventory-management-app-act12.firebasestorage.app',
    iosBundleId: 'com.example.act12InventoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqaxaSIwEGbgFSOgi8jDNpTK7bULqsVgY',
    appId: '1:1038460710831:web:2cee2f7836ce325317c95a',
    messagingSenderId: '1038460710831',
    projectId: 'inventory-management-app-act12',
    authDomain: 'inventory-management-app-act12.firebaseapp.com',
    storageBucket: 'inventory-management-app-act12.firebasestorage.app',
    measurementId: 'G-3Y3X36QEYW',
  );
}
